package com.android.lvicto.sanskriter.util

// DO NOT TOUCH !! //

object SandhiEngine {

    fun decomposeSandhi(sandhi: String): List<String>? {
        return sandhiMapDecompose[sandhi]
    }

    private val sandhiMapDecompose = mapOf(
        // table 2.1 vowels
        // line 1
        "ā" to arrayListOf("a a", "ā a"),
        "ya" to arrayListOf("i a", "ī a"),
        "va" to arrayListOf("u a", "ū a"),
        "ra" to arrayListOf("ṛ a"),
        "e" to arrayListOf("e a"),
        "ā a" to arrayListOf("ai a"),
        "o" to arrayListOf("o a"),
        "āva" to arrayListOf("au a"),

        // line 2
        "ā" to arrayListOf("a ā", "ā ā"),
        "yā" to arrayListOf("i ā", "ī ā"),
        "va" to arrayListOf("u ā", "ū ā"),
        "ra" to arrayListOf("ṛ ā"),
        "e" to arrayListOf("e ā"),
        "ā a" to arrayListOf("ai ā"),
        "o" to arrayListOf("o ā"),
        "āva" to arrayListOf("au ā"),

        // line 3
        "e" to arrayListOf("a i", "ā i", "ā ī", "ā ī"),
        "ī" to arrayListOf("ī ī", "ī ī", "i i", "ī i"),
        "vi" to arrayListOf("u i", "ū i"),
        "vī" to arrayListOf("u ī", "ū ī"),
        "ri" to arrayListOf("ṛ i"),
        "rī" to arrayListOf("ṛ ī"),
        "a i" to arrayListOf("e i", "o i"),
        "a ī" to arrayListOf("e ī", "o ī"),
        "āvi" to arrayListOf("au i"),

        // line 4
        "o" to arrayListOf("a u", "ā u", "a ū", "ā ū"),
        "yu" to arrayListOf("i u", "ī u"),
        "yū" to arrayListOf("i ū", "ī ū"),
        "ū" to arrayListOf("u u", "u ū", "ū u", "ū ū"),
        "ṛu" to arrayListOf("ṛ u"),
        "ṛū" to arrayListOf("ṛ ū"),
        "a u" to arrayListOf("e u"),
        "a ū" to arrayListOf("e ū"),
        "ā u" to arrayListOf("ai u"),
        "ā ū" to arrayListOf("ai ū"),
        "a u" to arrayListOf("o u"),
        "a ū" to arrayListOf("o ū"),
        "āvu" to arrayListOf("au u"),
        "āvū" to arrayListOf("au ū"),

        // line 5
        "ar" to arrayListOf("a ṛ", "ā ṛ"),
        "yṛ" to arrayListOf("i ṛ", "ī ṛ"),
        "vṛ" to arrayListOf("u ṛ", "ū ṛ"),
        "ṝ" to arrayListOf("ṛ ṛ"),
        "a ṛ" to arrayListOf("e ṛ", "o ṛ"),
        "ā ṛ" to arrayListOf("ai ṛ"),
        "āvṛ" to arrayListOf("au ṛ"),

        // line 6
        "ai" to arrayListOf("a e", "ā e"),
        "ye" to arrayListOf("i e", "ī e"),
        "ve" to arrayListOf("u e", "ū e"),
        "re" to arrayListOf("ṛ e"),
        "a e" to arrayListOf("e e", "o e"),
        "ā e" to arrayListOf("ai e"),
        "āve" to arrayListOf("au e"),

        // line 7
        "ai" to arrayListOf("a ai", "ā ai"),
        "yai" to arrayListOf("i ai", "ī ai"),
        "vai" to arrayListOf("u ai", "ū ai"),
        "rai" to arrayListOf("ṛ ai"),
        "a ai" to arrayListOf("e ai", "o ai"),
        "ā ai" to arrayListOf("ā ai"),
        "āvai" to arrayListOf("au ai"),

        // line 8
        "au" to arrayListOf("a o", "ā o"),
        "yo" to arrayListOf("i o", "ī o"),
        "vo" to arrayListOf("u o", "ū o"),
        "ro" to arrayListOf("ṛ o"),
        "a o" to arrayListOf("e o", "o o"),
        "ā o" to arrayListOf("ai o"),
        "āvo" to arrayListOf("au o"),

        // line 9
        "au" to arrayListOf("a au", "ā au"),
        "yau" to arrayListOf("i au", "ī au"),
        "vau" to arrayListOf("u au", "ū au"),
        "rau" to arrayListOf("ṛ au"),
        "a au" to arrayListOf("e au", "o au"),
        "ā au" to arrayListOf("ai au"),
        "āvau" to arrayListOf("au au"),
        // end table 2.1 vowels ā ī ū ṛ ṝ ḷ ḹ

        // table 2.1 consonants
        // line 1 (k/kh)
        "kk" to arrayListOf("k k"), "kkh" to arrayListOf("k kh"),
        "ṭk" to arrayListOf("ṭ k"), "ṭkh" to arrayListOf("ṭ kh"),
        "tk" to arrayListOf("t k"), "tkh" to arrayListOf("t kh"),
        "pk" to arrayListOf("p k"), "pkh" to arrayListOf("p kh"),
        "ṅk" to arrayListOf("ṅ k"), "ṅkh" to arrayListOf("ṅ kh"),
        "nk" to arrayListOf("n k"), "nkh" to arrayListOf("n kh"),
        "mk" to arrayListOf("m k"), "mkh" to arrayListOf("m kh"),
        "iḥ k" to arrayListOf("iḥ k", "ir k"), "iḥ kh" to arrayListOf("iḥ kh", "ir kh"),
        "īḥ k" to arrayListOf("īḥ k", "īr k"), "īḥ kh" to arrayListOf("īḥ kh", "īr kh"),
        "uḥ k" to arrayListOf("uḥ k", "ur k"), "uḥ kh" to arrayListOf("uḥ kh", "ur kh"),
        "ūḥ k" to arrayListOf("ūḥ k", "ūr k"), "ūḥ kh" to arrayListOf("ūḥ kh", "ūr kh"),
        "eḥ k" to arrayListOf("eḥ k", "er k"), "eḥ kh" to arrayListOf("eḥ kh", "er kh"),
        "oḥ k" to arrayListOf("oḥ k", "or k"), "oḥ kh" to arrayListOf("oḥ kh", "or kh"),
        "ṛḥ k" to arrayListOf("ṛḥ k", "ṛr k"), "ṛḥ kh" to arrayListOf("ṛḥ kh", "ṛr kh"),
        "ṝḥ k" to arrayListOf("ṝḥ k", "ṝr k"), "ṝḥ kh" to arrayListOf("ṝḥ kh", "ṝr kh"),
        "ḷḥ k" to arrayListOf("ḷḥ k", "ḷr k"), "ḷḥ kh" to arrayListOf("ḷḥ kh", "ḷr kh"),
        "ḹḥ k" to arrayListOf("ḹḥ k", "ḷr k"), "ḹḥ kh" to arrayListOf("ḹḥ kh", "ḹr kh"),
        "āḥ k" to arrayListOf("āḥ k", "ār k"), "āḥ kh" to arrayListOf("āḥ kh", "ār kh"),
        "aḥ k" to arrayListOf("aḥ k", "ār k"), "aḥ kh" to arrayListOf("aḥ kh", "ar kh"),

        // line 2 (g/gh)
        "gg" to arrayListOf("k g"), "ggh" to arrayListOf("k gh"),
        "ḍg" to arrayListOf("ṭ g"), "ḍkh" to arrayListOf("ṭ gh"),
        "dg" to arrayListOf("t g"), "tgh" to arrayListOf("d gh"),
        "bg" to arrayListOf("p g"), "bgh" to arrayListOf("p gh"),
        "ṅg" to arrayListOf("ṅ g"), "ṅgh" to arrayListOf("ṅ gh"),
        "ng" to arrayListOf("n g"), "ngh" to arrayListOf("n gh"),
        "ṃg" to arrayListOf("m g"), "ṃgh" to arrayListOf("m gh"),
        "irg" to arrayListOf("iḥ g", "ir g"), "irgh" to arrayListOf("iḥ gh", "ir gh"),
        "īrg" to arrayListOf("īḥ g", "īr g"), "īrgh" to arrayListOf("īḥ gh", "īr gh"),
        "urg" to arrayListOf("uḥ g", "ur g"), "urgh" to arrayListOf("uḥ gh", "uḥ gh"),
        "ūrg" to arrayListOf("ūḥ g", "ūr g"), "ūrgh" to arrayListOf("ūḥ gh", "ūr gh"),
        "erg" to arrayListOf("eḥ g", "er g"), "ergh" to arrayListOf("eḥ gh", "er gh"),
        "org" to arrayListOf("oḥ g"), "orgh" to arrayListOf("oḥ gh"),
        "org" to arrayListOf("or g"), "orgh" to arrayListOf("or gh"),
        "ṛrg" to arrayListOf("ṛḥ g", "ṛr g"), "ṛrgh" to arrayListOf("ṛḥ gh", "ṛr gh"),
        "ṝrg" to arrayListOf("ṝḥ g", "ṝr g"), "ṝrgh" to arrayListOf("ṝḥ gh", "ṝr gh"),
        "ḷrg" to arrayListOf("ḷḥ g", "ḷr g"), "ḷrgh" to arrayListOf("ḷḥ gh", "ḷr gh"),
        "ḹrg" to arrayListOf("ḹḥ g", "ḷr g"), "ḹrgh" to arrayListOf("ḹḥ gh", "ḹr gh"),
        "ā g" to arrayListOf("āḥ g"), "ā gh" to arrayListOf("āḥ gh"),
        "o g" to arrayListOf("a g"), "o gh" to arrayListOf("a gh"),

        // line 3 (c/ch)
        "kc" to arrayListOf("k c"), "kch" to arrayListOf("k ch"),
        "ṭc" to arrayListOf("ṭ c"), "ṭch" to arrayListOf("ṭ ch"),
        "cc" to arrayListOf("t c"), "cch" to arrayListOf("d ch"),
        "pc" to arrayListOf("p c"), "pch" to arrayListOf("p ch"),
        "ṅc" to arrayListOf("ṅ c"), "ṅch" to arrayListOf("ṅ ch"),
        "mś" to arrayListOf("n c"), "mś" to arrayListOf("n ch"),
        "ṃc" to arrayListOf("m c"), "ṃch" to arrayListOf("m ch"),
        "iśc" to arrayListOf("iḥ c", "ir c"), "iśch" to arrayListOf("iḥ ch", "ir ch"),
        "īśc" to arrayListOf("īḥ c", "īr c"), "īśch" to arrayListOf("īḥ ch", "īr ch"),
        "uśc" to arrayListOf("uḥ c", "ur c"), "uśch" to arrayListOf("uḥ ch", "uḥ ch"),
        "ūśc" to arrayListOf("ūḥ c", "ūr c"), "ūśch" to arrayListOf("ūḥ ch", "ūr ch"),
        "eśc" to arrayListOf("eḥ c", "er c"), "eśch" to arrayListOf("eḥ ch", "er ch"),
        "ośc" to arrayListOf("oḥ c"), "orch" to arrayListOf("oḥ ch"),
        "ośc" to arrayListOf("or c"), "ośch" to arrayListOf("or ch"),
        "ṛśc" to arrayListOf("ṛḥ c", "ṛr c"), "ṛśch" to arrayListOf("ṛḥ ch", "ṛr ch"),
        "ṝśc" to arrayListOf("ṝḥ c", "ṝr c"), "ṝśch" to arrayListOf("ṝḥ ch", "ṝr ch"),
        "ḷśc" to arrayListOf("ḷḥ c", "ḷr c"), "ḷśch" to arrayListOf("ḷḥ ch", "ḷr ch"),
        "ḹśc" to arrayListOf("ḹḥ c", "ḷr c"), "ḹśch" to arrayListOf("ḹḥ ch", "ḹr ch"),
        "āśc" to arrayListOf("āḥ c"), "āśch" to arrayListOf("āḥ ch"),
        "aśc" to arrayListOf("aḥ c"), "aśch" to arrayListOf("aḥ ch"),

        // line 4 (j/jh)
        "gj" to arrayListOf("k j"), "gjh" to arrayListOf("k jh"),
        "ḍj" to arrayListOf("ṭ j"), "ḍkh" to arrayListOf("ṭ jh"),
        "jj" to arrayListOf("t j"), "jjh" to arrayListOf("d jh"),
        "bj" to arrayListOf("p j"), "bjh" to arrayListOf("p jh"),
        "ṅj" to arrayListOf("ṅ j"), "ṅjh" to arrayListOf("ṅ jh"),
        "ñj" to arrayListOf("n j"), "ñjh" to arrayListOf("n jh"),
        "ṃj" to arrayListOf("m j"), "ṃjh" to arrayListOf("m jh"),
        "irj" to arrayListOf("iḥ j", "ir j"), "irjh" to arrayListOf("iḥ jh", "ir jh"),
        "īrj" to arrayListOf("īḥ j", "īr j"), "īrjh" to arrayListOf("īḥ jh", "īr jh"),
        "urj" to arrayListOf("uḥ j", "ur j"), "urjh" to arrayListOf("uḥ jh", "uḥ jh"),
        "ūrj" to arrayListOf("ūḥ j", "ūr j"), "ūrjh" to arrayListOf("ūḥ jh", "ūr jh"),
        "erj" to arrayListOf("eḥ j", "er j"), "erjh" to arrayListOf("eḥ jh", "er jh"),
        "orj" to arrayListOf("oḥ j"), "orjh" to arrayListOf("oḥ jh"),
        "orj" to arrayListOf("or j"), "orjh" to arrayListOf("or jh"),
        "ṛrj" to arrayListOf("ṛḥ j", "ṛr j"), "ṛrjh" to arrayListOf("ṛḥ jh", "ṛr jh"),
        "ṝrj" to arrayListOf("ṝḥ j", "ṝr j"), "ṝrjh" to arrayListOf("ṝḥ jh", "ṝr jh"),
        "ḷrj" to arrayListOf("ḷḥ j", "ḷr j"), "ḷrjh" to arrayListOf("ḷḥ jh", "ḷr jh"),
        "ḹrj" to arrayListOf("ḹḥ j", "ḷr j"), "ḹrjh" to arrayListOf("ḹḥ jh", "ḹr jh"),
        "ā j" to arrayListOf("āḥ j"), "ā jh" to arrayListOf("āḥ jh"),
        "o j" to arrayListOf("a j"), "o jh" to arrayListOf("a jh"),

        // line 5 (ṭ/ṭh)
        "kṭ" to arrayListOf("k ṭ"), "kṭh" to arrayListOf("k ṭh"),
        "ṭṭ" to arrayListOf("ṭ ṭ"), "ṭṭh" to arrayListOf("ṭ ṭh"),
        "ṭṭ" to arrayListOf("t ṭ"), "ṭṭh" to arrayListOf("d ṭh"),
        "pṭ" to arrayListOf("p ṭ"), "pṭh" to arrayListOf("p ṭh"),
        "ṅṭ" to arrayListOf("ṅ ṭ"), "ṅṭh" to arrayListOf("ṅ ṭh"),
        "ṃṣṭ" to arrayListOf("n ṭ"), "ṃṣṭh" to arrayListOf("n ṭh"),
        "ṃṭ" to arrayListOf("m ṭ"), "ṃṭh" to arrayListOf("m ṭh"),
        "iṣṭ" to arrayListOf("iḥ ṭ", "ir ṭ"), "iṣṭh" to arrayListOf("iḥ ṭh", "ir ṭh"),
        "īṣṭ" to arrayListOf("īḥ ṭ", "īr ṭ"), "īṣṭh" to arrayListOf("īḥ ṭh", "īr ṭh"),
        "uṣṭ" to arrayListOf("uḥ ṭ", "ur ṭ"), "uṣṭh" to arrayListOf("uḥ ṭh", "uḥ ṭh"),
        "ūṣṭ" to arrayListOf("ūḥ ṭ", "ūr ṭ"), "ūṣṭh" to arrayListOf("ūḥ ṭh", "ūr ṭh"),
        "eṣṭ" to arrayListOf("eḥ ṭ", "er ṭ"), "eṣṭh" to arrayListOf("eḥ ṭh", "er ṭh"),
        "oṣṭ" to arrayListOf("oḥ ṭ"), "orṭh" to arrayListOf("oḥ ṭh"),
        "oṣṭ" to arrayListOf("or ṭ"), "oṣṭh" to arrayListOf("or ṭh"),
        "ṛṣṭ" to arrayListOf("ṛḥ ṭ", "ṛr ṭ"), "ṛṣṭh" to arrayListOf("ṛḥ ṭh", "ṛr ṭh"),
        "ṝṣṭ" to arrayListOf("ṝḥ ṭ", "ṝr ṭ"), "ṝṣṭh" to arrayListOf("ṝḥ ṭh", "ṝr ṭh"),
        "ḷṣṭ" to arrayListOf("ḷḥ ṭ", "ḷr ṭ"), "ḷṣṭh" to arrayListOf("ḷḥ ṭh", "ḷr ṭh"),
        "ḹṣṭ" to arrayListOf("ḹḥ ṭ", "ḷr ṭ"), "ḹṣṭh" to arrayListOf("ḹḥ ṭh", "ḹr ṭh"),
        "āṣṭ" to arrayListOf("āḥ ṭ"), "āṣṭh" to arrayListOf("āḥ ṭh"),
        "aṣṭ" to arrayListOf("aḥ ṭ"), "aṣṭh" to arrayListOf("aḥ ṭh"),

        // line 6 (ḍ/ḍh)
        "gḍ" to arrayListOf("k ḍ"), "gḍh" to arrayListOf("k ḍh"),
        "ḍḍ" to arrayListOf("ḍ ḍ"), "ḍḍh" to arrayListOf("ḍ ḍh"),
        "ḍḍ" to arrayListOf("t ḍ"), "ḍḍh" to arrayListOf("d ḍh"),
        "bḍ" to arrayListOf("p ḍ"), "bḍh" to arrayListOf("p ḍh"),
        "ṅḍ" to arrayListOf("ṅ ḍ"), "ṅḍh" to arrayListOf("ṅ ḍh"),
        "ṇḍ" to arrayListOf("n ḍ"), "ṇḍh" to arrayListOf("n ḍh"),
        "ṃḍ" to arrayListOf("m ḍ"), "ṃḍh" to arrayListOf("m ḍh"),
        "irḍ" to arrayListOf("iḥ ḍ", "ir ḍ"), "irḍh" to arrayListOf("iḥ ḍh", "ir ḍh"),
        "īrḍ" to arrayListOf("īḥ ḍ", "īr ḍ"), "īrḍh" to arrayListOf("īḥ ḍh", "īr ḍh"),
        "urḍ" to arrayListOf("uḥ ḍ", "ur ḍ"), "urḍh" to arrayListOf("uḥ ḍh", "uḥ ḍh"),
        "ūrḍ" to arrayListOf("ūḥ ḍ", "ūr ḍ"), "ūrḍh" to arrayListOf("ūḥ ḍh", "ūr ḍh"),
        "erḍ" to arrayListOf("eḥ ḍ", "er ḍ"), "erḍh" to arrayListOf("eḥ ḍh", "er ḍh"),
        "orḍ" to arrayListOf("oḥ ḍ"), "orḍh" to arrayListOf("oḥ ḍh"),
        "orḍ" to arrayListOf("or ḍ"), "orḍh" to arrayListOf("or ḍh"),
        "ṛrḍ" to arrayListOf("ṛḥ ḍ", "ṛr ḍ"), "ṛrḍh" to arrayListOf("ṛḥ ḍh", "ṛr ḍh"),
        "ṝrḍ" to arrayListOf("ṝḥ ḍ", "ṝr ḍ"), "ṝrḍh" to arrayListOf("ṝḥ ḍh", "ṝr ḍh"),
        "ḷrḍ" to arrayListOf("ḷḥ ḍ", "ḷr ḍ"), "ḷrḍh" to arrayListOf("ḷḥ ḍh", "ḷr ḍh"),
        "ḹrḍ" to arrayListOf("ḹḥ ḍ", "ḷr ḍ"), "ḹrḍh" to arrayListOf("ḹḥ ḍh", "ḹr ḍh"),
        "ā ḍ" to arrayListOf("āḥ ḍ"), "ā ḍh" to arrayListOf("āḥ ḍh"),
        "o ḍ" to arrayListOf("aḥ ḍ"), "o ḍh" to arrayListOf("aḥ ḍh"),

        // line 7 (t/th)
        "kt" to arrayListOf("k t"), "kth" to arrayListOf("k th"),
        "ṭt" to arrayListOf("ṭ t"), "tth" to arrayListOf("ṭ th"),
        "tt" to arrayListOf("t t"), "tth" to arrayListOf("d th"),
        "pt" to arrayListOf("p t"), "pth" to arrayListOf("p th"),
        "ṅt" to arrayListOf("ṅ t"), "ṅth" to arrayListOf("ṅ th"),
        "ṃṣt" to arrayListOf("n t"), "ṃṣth" to arrayListOf("n th"),
        "ṃt" to arrayListOf("m t"), "ṃth" to arrayListOf("m th"),
        "ist" to arrayListOf("iḥ t", "ir t"), "isth" to arrayListOf("iḥ th", "ir th"),
        "īst" to arrayListOf("īḥ t", "īr t"), "īsth" to arrayListOf("īḥ th", "īr th"),
        "ust" to arrayListOf("uḥ t", "ur t"), "usth" to arrayListOf("uḥ th", "uḥ th"),
        "ūst" to arrayListOf("ūḥ t", "ūr t"), "ūsth" to arrayListOf("ūḥ th", "ūr th"),
        "est" to arrayListOf("eḥ t", "er t"), "esth" to arrayListOf("eḥ th", "er th"),
        "ost" to arrayListOf("oḥ t"), "orth" to arrayListOf("oḥ th"),
        "ost" to arrayListOf("or t"), "osth" to arrayListOf("or th"),
        "ṛst" to arrayListOf("ṛḥ t", "ṛr t"), "ṛsth" to arrayListOf("ṛḥ th", "ṛr th"),
        "ṝst" to arrayListOf("ṝḥ t", "ṝr t"), "ṝsth" to arrayListOf("ṝḥ th", "ṝr th"),
        "ḷst" to arrayListOf("ḷḥ t", "ḷr t"), "ḷsth" to arrayListOf("ḷḥ th", "ḷr th"),
        "ḹst" to arrayListOf("ḹḥ t", "ḷr t"), "ḹsth" to arrayListOf("ḹḥ th", "ḹr th"),
        "āst" to arrayListOf("āḥ t"), "āsth" to arrayListOf("āḥ th"),
        "ast" to arrayListOf("aḥ t"), "asth" to arrayListOf("aḥ th"),

        // line 8 (d/dh)
        "gd" to arrayListOf("k d"), "gdh" to arrayListOf("k dh"),
        "dḍ" to arrayListOf("ṭ d"), "ddh" to arrayListOf("ṭ dh"),
        "dd" to arrayListOf("t d"), "ddh" to arrayListOf("d dh"),
        "bd" to arrayListOf("p d"), "bdh" to arrayListOf("p dh"),
        "ṅd" to arrayListOf("ṅ d"), "ṅdh" to arrayListOf("ṅ dh"),
        "ṇd" to arrayListOf("n d"), "ṇdh" to arrayListOf("n dh"),
        "ṃd" to arrayListOf("m d"), "ṃdh" to arrayListOf("m dh"),
        "ird" to arrayListOf("iḥ d", "ir d"), "irdh" to arrayListOf("iḥ dh", "ir dh"),
        "īrd" to arrayListOf("īḥ d", "īr d"), "īrdh" to arrayListOf("īḥ dh", "īr dh"),
        "urd" to arrayListOf("uḥ d", "ur d"), "urdh" to arrayListOf("uḥ dh", "uḥ dh"),
        "ūrd" to arrayListOf("ūḥ d", "ūr d"), "ūrdh" to arrayListOf("ūḥ dh", "ūr dh"),
        "erd" to arrayListOf("eḥ d", "er d"), "erdh" to arrayListOf("eḥ dh", "er dh"),
        "ord" to arrayListOf("oḥ d"), "ordh" to arrayListOf("oḥ dh"),
        "ord" to arrayListOf("or d"), "ordh" to arrayListOf("or dh"),
        "ṛrd" to arrayListOf("ṛḥ d", "ṛr d"), "ṛrdh" to arrayListOf("ṛḥ dh", "ṛr dh"),
        "ṝrd" to arrayListOf("ṝḥ d", "ṝr d"), "ṝrdh" to arrayListOf("ṝḥ dh", "ṝr dh"),
        "ḷrd" to arrayListOf("ḷḥ d", "ḷr d"), "ḷrdh" to arrayListOf("ḷḥ dh", "ḷr dh"),
        "ḹrd" to arrayListOf("ḹḥ d", "ḷr d"), "ḹrdh" to arrayListOf("ḹḥ dh", "ḹr dh"),
        "ā d" to arrayListOf("āḥ d"), "ā dh" to arrayListOf("āḥ dh"),
        "o d" to arrayListOf("aḥ d"), "o dh" to arrayListOf("aḥ dh"),

        // line 9 (p/ph)
        "kp" to arrayListOf("k p"), "kph" to arrayListOf("k ph"),
        "ṭp" to arrayListOf("ṭ p"), "tph" to arrayListOf("ṭ ph"),
        "tp" to arrayListOf("t p"), "tph" to arrayListOf("d ph"),
        "pp" to arrayListOf("p p"), "pph" to arrayListOf("p ph"),
        "ṅp" to arrayListOf("ṅ p"), "ṅph" to arrayListOf("ṅ ph"),
        "ṃṣp" to arrayListOf("n p"), "ṃṣph" to arrayListOf("n ph"),
        "ṃp" to arrayListOf("m p"), "ṃph" to arrayListOf("m ph"),
        "iḥ p" to arrayListOf("iḥ p", "ir p"), "iḥ ph" to arrayListOf("iḥ ph", "ir ph"),
        "īḥ p" to arrayListOf("īḥ p", "īr p"), "īḥ ph" to arrayListOf("īḥ ph", "īr ph"),
        "uḥ p" to arrayListOf("uḥ p", "ur p"), "uḥ ph" to arrayListOf("uḥ ph", "uḥ ph"),
        "ūḥ p" to arrayListOf("ūḥ p", "ūr p"), "ūḥ ph" to arrayListOf("ūḥ ph", "ūr ph"),
        "eḥ p" to arrayListOf("eḥ p", "er p"), "eḥ ph" to arrayListOf("eḥ ph", "er ph"),
        "oḥ p" to arrayListOf("oḥ p"), "orph" to arrayListOf("oḥ ph"),
        "oḥ p" to arrayListOf("or p"), "oḥ ph" to arrayListOf("or ph"),
        "ṛḥ p" to arrayListOf("ṛḥ p", "ṛr p"), "ṛḥ ph" to arrayListOf("ṛḥ ph", "ṛr ph"),
        "ṝḥ p" to arrayListOf("ṝḥ p", "ṝr p"), "ṝḥ ph" to arrayListOf("ṝḥ ph", "ṝr ph"),
        "ḷḥ p" to arrayListOf("ḷḥ p", "ḷr p"), "ḷḥ ph" to arrayListOf("ḷḥ ph", "ḷr ph"),
        "ḹḥ p" to arrayListOf("ḹḥ p", "ḷr p"), "ḹḥ ph" to arrayListOf("ḹḥ ph", "ḹr ph"),
        "āḥ p" to arrayListOf("āḥ p"), "āḥ ph" to arrayListOf("āḥ ph"),
        "aḥ p" to arrayListOf("aḥ p"), "aḥ ph" to arrayListOf("aḥ ph"),

        // line 10 (b/bh)
        "gp" to arrayListOf("k p"), "gph" to arrayListOf("k ph"),
        "ḍp" to arrayListOf("ṭ p"), "ḍph" to arrayListOf("ṭ ph"),
        "dp" to arrayListOf("t p"), "dph" to arrayListOf("t ph"),
        "bp" to arrayListOf("p p"), "bph" to arrayListOf("p ph"),
        "ṅp" to arrayListOf("ṅ p"), "ṅph" to arrayListOf("ṅ ph"),
        "np" to arrayListOf("n p"), "np" to arrayListOf("n ph"),
        "ṃp" to arrayListOf("m p"), "ṃph" to arrayListOf("m ph"),
        "irp" to arrayListOf("iḥ p", "ir p"), "irph" to arrayListOf("iḥ ph", "ir ph"),
        "īrp" to arrayListOf("īḥ p", "īr p"), "īrph" to arrayListOf("īḥ ph", "īr ph"),
        "urp" to arrayListOf("uḥ p", "ur p"), "urph" to arrayListOf("uḥ ph", "uḥ ph"),
        "ūrp" to arrayListOf("ūḥ p", "ūr p"), "ūrph" to arrayListOf("ūḥ ph", "ūr ph"),
        "erp" to arrayListOf("eḥ p", "er p"), "erph" to arrayListOf("eḥ ph", "er ph"),
        "orp" to arrayListOf("oḥ p"), "orph" to arrayListOf("oḥ ph"),
        "orp" to arrayListOf("or p"), "orph" to arrayListOf("or ph"),
        "ṛrb" to arrayListOf("ṛḥ b", "ṛr b"), "ṛrbh" to arrayListOf("ṛḥ bh", "ṛr bh"),
        "ṝrb" to arrayListOf("ṝḥ b", "ṝr b"), "ṝrbh" to arrayListOf("ṝḥ bh", "ṝr bh"),
        "ḷrb" to arrayListOf("ḷḥ b", "ḷr b"), "ḷrbh" to arrayListOf("ḷḥ bh", "ḷr bh"),
        "ḹrb" to arrayListOf("ḹḥ b", "ḷr b"), "ḹrbh" to arrayListOf("ḹḥ bh", "ḹr bh"),
        "ā p" to arrayListOf("āḥ p"), "ā ph" to arrayListOf("āḥ ph"),
        "o p" to arrayListOf("aḥ p"), "o ph" to arrayListOf("aḥ ph"),

        // line 11 (n/m)
        "ṅn" to arrayListOf("k n"), "ṅm" to arrayListOf("k m"),
        "ṇn" to arrayListOf("ṭ n"), "ṇm" to arrayListOf("ṭ m"),
        "jn" to arrayListOf("t n"), "jm" to arrayListOf("d m"),
        "bn" to arrayListOf("m n"), "bm" to arrayListOf("m m"),
        "ṅn" to arrayListOf("ṅ n"), "ṅm" to arrayListOf("ṅ m"),
        "ñn" to arrayListOf("n n"), "ñm" to arrayListOf("n m"),
        "ṃn" to arrayListOf("ṃ n"), "ṃm" to arrayListOf("ṃ m"),
        "irn" to arrayListOf("iḥ n", "ir n"), "irm" to arrayListOf("iḥ m", "ir m"),
        "īrn" to arrayListOf("īḥ n", "īr n"), "īrm" to arrayListOf("īḥ m", "īr m"),
        "urn" to arrayListOf("uḥ n", "ur n"), "urm" to arrayListOf("uḥ m", "uḥ m"),
        "ūrn" to arrayListOf("ūḥ n", "ūr n"), "ūrm" to arrayListOf("ūḥ m", "ūr m"),
        "ern" to arrayListOf("eḥ n", "er n"), "erm" to arrayListOf("eḥ m", "er m"),
        "orn" to arrayListOf("oḥ n"), "orm" to arrayListOf("oḥ m"),
        "orn" to arrayListOf("or n"), "orm" to arrayListOf("or m"),
        "ṛrn" to arrayListOf("ṛḥ n", "ṛr n"), "ṛrm" to arrayListOf("ṛḥ m", "ṛr m"),
        "ṝrn" to arrayListOf("ṝḥ n", "ṝr n"), "ṝrm" to arrayListOf("ṝḥ m", "ṝr m"),
        "ḷrn" to arrayListOf("ḷḥ n", "ḷr n"), "ḷrm" to arrayListOf("ḷḥ m", "ḷr m"),
        "ḹrn" to arrayListOf("ḹḥ n", "ḷr n"), "ḹrm" to arrayListOf("ḹḥ m", "ḹr m"),
        "ā n" to arrayListOf("āḥ n"), "ā m" to arrayListOf("āḥ m"),
        "o n" to arrayListOf("a n"), "o m" to arrayListOf("aḥ m"),

        // line 12 (y/v)
        "gy" to arrayListOf("k y"), "gv" to arrayListOf("k v"),
        "ḍy" to arrayListOf("ṭ y"), "ḍv" to arrayListOf("ṭ v"),
        "dy" to arrayListOf("t y"), "dv" to arrayListOf("d v"),
        "by" to arrayListOf("p y"), "bv" to arrayListOf("p v"),
        "ṅy" to arrayListOf("ṅ y"), "ṅv" to arrayListOf("ṅ v"),
        "ny" to arrayListOf("n y"), "nv" to arrayListOf("n v"),
        "ṃy" to arrayListOf("m y"), "ṃv" to arrayListOf("m v"),
        "iry" to arrayListOf("iḥ y", "ir y"), "irv" to arrayListOf("iḥ v", "ir v"),
        "īry" to arrayListOf("īḥ y", "īr y"), "īrv" to arrayListOf("īḥ v", "īr v"),
        "ury" to arrayListOf("uḥ y", "ur y"), "urv" to arrayListOf("uḥ v", "uḥ v"),
        "ūry" to arrayListOf("ūḥ y", "ūr y"), "ūrv" to arrayListOf("ūḥ v", "ūr v"),
        "ery" to arrayListOf("eḥ y", "er y"), "erv" to arrayListOf("eḥ v", "er v"),
        "ory" to arrayListOf("oḥ y"), "orv" to arrayListOf("oḥ v"),
        "ory" to arrayListOf("or y"), "orv" to arrayListOf("or v"),
        "ṛry" to arrayListOf("ṛḥ y", "ṛr y"), "ṛrv" to arrayListOf("ṛḥ v", "ṛr v"),
        "ṝry" to arrayListOf("ṝḥ y", "ṝr y"), "ṝrv" to arrayListOf("ṝḥ v", "ṝr v"),
        "ḷry" to arrayListOf("ḷḥ y", "ḷr y"), "ḷrv" to arrayListOf("ḷḥ v", "ḷr v"),
        "ḹry" to arrayListOf("ḹḥ y", "ḷr y"), "ḹrv" to arrayListOf("ḹḥ v", "ḹr v"),
        "ā y" to arrayListOf("āḥ y"), "ā v" to arrayListOf("āḥ v"),
        "o y" to arrayListOf("a y"), "o v" to arrayListOf("aḥ v"),

        // line 13 (r)
        "gr" to arrayListOf("k r"),
        "ḍr" to arrayListOf("ṭ r"),
        "dr" to arrayListOf("t r"),
        "br" to arrayListOf("p r"),
        "ṅr" to arrayListOf("ṅ r"),
        "nr" to arrayListOf("n r"),
        "ṃr" to arrayListOf("m r"),
        "ī r" to arrayListOf("iḥ r", "ir r", "īḥ r", "īr r"),
        "ū r" to arrayListOf("uḥ r", "ur r", "ūḥ r", "ūr r"),
        "e r" to arrayListOf("eḥ r", "er r"),
        "o r" to arrayListOf("oḥ r", "or r", "āḥ r"),
        "ṛ r" to arrayListOf("ṛḥ r", "ṛr r"),
        "ṝ r" to arrayListOf("ṝḥ r", "ṝr r"),
        "ḷ r" to arrayListOf("ḷḥ r", "ḷr r"),
        "ḹ r" to arrayListOf("ḹḥ r", "ḹr r"),
        "ā r" to arrayListOf("āḥ r"),
        "o r" to arrayListOf("aḥ r"),
        
        // line 14 (l)
        "gl" to arrayListOf("k l"),
        "ḍl" to arrayListOf("ṭ l"),
        "ll" to arrayListOf("t l"),
        "bl" to arrayListOf("p l"),
        "ṅl" to arrayListOf("ṅ l"),
        "?l" to arrayListOf("n l"), // todo add l with omkara
        "ṃl" to arrayListOf("m l"),
        "irl" to arrayListOf("iḥ l", "ir l"),
        "īrl" to arrayListOf("īḥ l", "īr l"),
        "ūrl" to arrayListOf("uḥ l", "ur l"),
        "ūrl" to arrayListOf("ūḥ l", "ūr l"),
        "erl" to arrayListOf("eḥ l", "er l"),
        "orl" to arrayListOf("oḥ l", "or l"),
        "ṛrl" to arrayListOf("ṛḥ l", "ṛr l"),
        "ṝrl" to arrayListOf("ṝḥ l", "ṝr l"),
        "ḷrl" to arrayListOf("ḷḥ l", "ḷr l"),
        "ḹrl" to arrayListOf("ḹḥ l", "ḹr l"),
        "ā l" to arrayListOf("āḥ l"),
        "o l" to arrayListOf("aḥ l"),

        // line 15 (ś)
        "kś" to arrayListOf("k ś"),
        "ṭś" to arrayListOf("ṭ ś"),
        "cch" to arrayListOf("t ś"),    // ch
        "bp" to arrayListOf("p ś"),
        "ṅś" to arrayListOf("ṅ ś"),
        "ñś" to arrayListOf("n ś"),
        "ñch" to arrayListOf("n ś"),
        "ṃś" to arrayListOf("m ś"),
        "iḥ ś" to arrayListOf("iḥ ś", "ir ś"),
        "īḥ ś" to arrayListOf("īḥ ś", "īr ś"),
        "ūḥ ś" to arrayListOf("uḥ ś", "ur ś"),
        "ūḥ ś" to arrayListOf("ūḥ ś", "ūr ś"),
        "eḥ ś" to arrayListOf("eḥ ś", "er ś"),
        "oḥ ś" to arrayListOf("oḥ ś", "or ś"),
        "ṛḥ ś" to arrayListOf("ṛḥ ś", "ṛr ś"),
        "ṝḥ ś" to arrayListOf("ṝḥ ś", "ṝr ś"),
        "ḷḥ ś" to arrayListOf("ḷḥ ś", "ḷr ś"),
        "ḹḥ ś" to arrayListOf("ḹḥ ś", "ḹr ś"),
        "āḥ ś" to arrayListOf("āḥ ś"),
        "aḥ ś" to arrayListOf("aḥ ś"),

        // line 16 (ṣ/s)
        "kṣ" to arrayListOf("k ṣ"), "ks" to arrayListOf("k s"),
        "ṭṣ" to arrayListOf("ṭ ṣ"), "ts" to arrayListOf("ṭ s"),
        "tṣ" to arrayListOf("t ṣ"), "ts" to arrayListOf("d s"),
        "pṣ" to arrayListOf("p ṣ"), "ps" to arrayListOf("p s"),
        "ṅṣ" to arrayListOf("ṅ ṣ"), "ṅs" to arrayListOf("ṅ s"),
        "nṣ" to arrayListOf("n ṣ"), "ns" to arrayListOf("n s"),
        "ṃṣ" to arrayListOf("m ṣ"), "ṃs" to arrayListOf("m s"),
        "iḥ ṣ" to arrayListOf("iḥ ṣ", "ir ṣ"), "iḥ s" to arrayListOf("iḥ s", "ir s"),
        "īḥ ṣ" to arrayListOf("īḥ ṣ", "īr ṣ"), "īḥ s" to arrayListOf("īḥ s", "īr s"),
        "uḥ ṣ" to arrayListOf("uḥ ṣ", "ur ṣ"), "uḥ s" to arrayListOf("uḥ s", "uḥ s"),
        "ūḥ ṣ" to arrayListOf("ūḥ ṣ", "ūr ṣ"), "ūḥ s" to arrayListOf("ūḥ s", "ūr s"),
        "eḥ ṣ" to arrayListOf("eḥ ṣ", "er ṣ"), "eḥ s" to arrayListOf("eḥ s", "er s"),
        "oḥ ṣ" to arrayListOf("oḥ ṣ"), "oḥ s" to arrayListOf("or s"),
        "oḥ ṣ" to arrayListOf("or ṣ"), "oḥ s" to arrayListOf("or s"),
        "ṛḥ ṣ" to arrayListOf("ṛḥ ṣ", "ṛr ṣ"), "ṛḥ s" to arrayListOf("ṛḥ s", "ṛr s"),
        "ṝḥ ṣ" to arrayListOf("ṝḥ ṣ", "ṝr ṣ"), "ṝḥ s" to arrayListOf("ṝḥ s", "ṝr s"),
        "ḷḥ ṣ" to arrayListOf("ḷḥ ṣ", "ḷr ṣ"), "ḷḥ s" to arrayListOf("ḷḥ s", "ḷr s"),
        "ḹḥ ṣ" to arrayListOf("ḹḥ ṣ", "ḷr ṣ"), "ḹḥ s" to arrayListOf("ḹḥ s", "ḹr s"),
        "āḥ ṣ" to arrayListOf("āḥ ṣ"), "āḥ s" to arrayListOf("āḥ s"),
        "aḥ ṣ" to arrayListOf("aḥ ṣ"), "aḥ s" to arrayListOf("aḥ s"),

        // line 17 (h)
        "ggh" to arrayListOf("k h"),
        "ḍdh" to arrayListOf("ṭ h"),
        "ddh" to arrayListOf("t h"),
        "bbh" to arrayListOf("p h"),
        "ṅh" to arrayListOf("ṅ h"),
        "nh" to arrayListOf("n h"),
        "ṃh" to arrayListOf("m h"),
        "irh" to arrayListOf("iḥ h", "ir h"),
        "īrh" to arrayListOf("īḥ h", "īr h"),
        "ūrh" to arrayListOf("uḥ h", "ur h"),
        "ūrh" to arrayListOf("ūḥ h", "ūr h"),
        "erh" to arrayListOf("eḥ h", "er h"),
        "orh" to arrayListOf("oḥ h", "or h"),
        "ṛrh" to arrayListOf("ṛḥ h", "ṛr h"),
        "ṝrh" to arrayListOf("ṝḥ h", "ṝr h"),
        "ḷrh" to arrayListOf("ḷḥ h", "ḷr h"),
        "ḹrh" to arrayListOf("ḹḥ h", "ḹr h"),
        "ā h" to arrayListOf("āḥ h"),
        "a h" to arrayListOf("aḥ h"),

        // line 18 (vowels)
        "ga" to arrayListOf("k a"),
        "ḍa" to arrayListOf("ṭ a"),
        "da" to arrayListOf("t a"),
        "ba" to arrayListOf("p a"),
        "ṅa" to arrayListOf("ṅ a"),
        "ga" to arrayListOf("k a"),
        "ṅṅa" to arrayListOf("ṅ a"),
        "na" to arrayListOf("n a"),
        "nna" to arrayListOf("n a"),
        "ma" to arrayListOf("m a"),
        "ira" to arrayListOf("iḥ a", "ir a"),
        "īra" to arrayListOf("īḥ a", "īr a"),
        "ūra" to arrayListOf("uḥ a", "ur a"),
        "ūra" to arrayListOf("ūḥ a", "ūr a"),
        "era" to arrayListOf("eḥ a", "er a"),
        "ora" to arrayListOf("oḥ a", "or a"),
        "ṛra" to arrayListOf("ṛḥ a", "ṛr a"),
        "ṝra" to arrayListOf("ṝḥ a", "ṝr a"),
        "ḷra" to arrayListOf("ḷḥ a", "ḷr a"),
        "ḹra" to arrayListOf("ḹḥ a", "ḹr a"),
        "ā a" to arrayListOf("āḥ a"),
        "'s" to arrayListOf("aḥ a"),

        "gā" to arrayListOf("k ā"),
        "ḍā" to arrayListOf("ṭ ā"),
        "dā" to arrayListOf("t ā"),
        "bā" to arrayListOf("p ā"),
        "ṅā" to arrayListOf("ṅ ā"),
        "gā" to arrayListOf("k ā"),
        "ṅṅā" to arrayListOf("ṅ ā"),
        "nā" to arrayListOf("n ā"),
        "nnā" to arrayListOf("n ā"),
        "mā" to arrayListOf("m ā"),
        "irā" to arrayListOf("iḥ ā", "ir ā"),
        "īrā" to arrayListOf("īḥ ā", "īr ā"),
        "ūrā" to arrayListOf("uḥ ā", "ur ā"),
        "ūrā" to arrayListOf("ūḥ ā", "ūr ā"),
        "erā" to arrayListOf("eḥ ā", "er ā"),
        "orā" to arrayListOf("oḥ ā", "or ā"),
        "ṛrā" to arrayListOf("ṛḥ ā", "ṛr ā"),
        "ṝrā" to arrayListOf("ṝḥ ā", "ṝr ā"),
        "ḷrā" to arrayListOf("ḷḥ ā", "ḷr ā"),
        "ḹrā" to arrayListOf("ḹḥ ā", "ḹr ā"),
        "ā ā" to arrayListOf("āḥ ā"),
        "o ā" to arrayListOf("aḥ ā"),

        "gi" to arrayListOf("k i"),
        "ḍi" to arrayListOf("ṭ i"),
        "di" to arrayListOf("t i"),
        "bi" to arrayListOf("p i"),
        "ṅi" to arrayListOf("ṅ i"),
        "gi" to arrayListOf("k i"),
        "ṅṅi" to arrayListOf("ṅ i"),
        "ni" to arrayListOf("n i"),
        "nni" to arrayListOf("n i"),
        "mi" to arrayListOf("m i"),
        "iri" to arrayListOf("iḥ i", "ir i"),
        "īri" to arrayListOf("īḥ i", "īr i"),
        "ūri" to arrayListOf("uḥ i", "ur i"),
        "ūri" to arrayListOf("ūḥ i", "ūr i"),
        "eri" to arrayListOf("eḥ i", "er i"),
        "ori" to arrayListOf("oḥ i", "or i"),
        "ṛri" to arrayListOf("ṛḥ i", "ṛr i"),
        "ṝri" to arrayListOf("ṝḥ i", "ṝr i"),
        "ḷri" to arrayListOf("ḷḥ i", "ḷr i"),
        "ḹri" to arrayListOf("ḹḥ i", "ḹr i"),
        "ā i" to arrayListOf("āḥ i"),
        "o i" to arrayListOf("aḥ i"),

        "gī" to arrayListOf("k ī"),
        "ḍī" to arrayListOf("ṭ ī"),
        "dī" to arrayListOf("t ī"),
        "bī" to arrayListOf("p ī"),
        "ṅī" to arrayListOf("ṅ ī"),
        "gī" to arrayListOf("k ī"),
        "ṅṅī" to arrayListOf("ṅ ī"),
        "nī" to arrayListOf("n ī"),
        "nnī" to arrayListOf("n ī"),
        "mī" to arrayListOf("m ī"),
        "irī" to arrayListOf("iḥ ī", "ir ī"),
        "īrī" to arrayListOf("īḥ ī", "īr ī"),
        "ūrī" to arrayListOf("uḥ ī", "ur ī"),
        "ūrī" to arrayListOf("ūḥ ī", "ūr ī"),
        "erī" to arrayListOf("eḥ ī", "er ī"),
        "orī" to arrayListOf("oḥ ī", "or ī"),
        "ṛrī" to arrayListOf("ṛḥ ī", "ṛr ī"),
        "ṝrī" to arrayListOf("ṝḥ ī", "ṝr ī"),
        "ḷrī" to arrayListOf("ḷḥ ī", "ḷr ī"),
        "ḹrī" to arrayListOf("ḹḥ ī", "ḹr ī"),
        "ā ī" to arrayListOf("āḥ ī"),
        "o ī" to arrayListOf("aḥ ī"),

        "gu" to arrayListOf("k u"),
        "ḍu" to arrayListOf("ṭ u"),
        "du" to arrayListOf("t u"),
        "bu" to arrayListOf("p u"),
        "ṅu" to arrayListOf("ṅ u"),
        "gu" to arrayListOf("k u"),
        "ṅṅu" to arrayListOf("ṅ u"),
        "nu" to arrayListOf("n u"),
        "nnu" to arrayListOf("n u"),
        "mu" to arrayListOf("m u"),
        "iru" to arrayListOf("iḥ u", "ir u"),
        "īru" to arrayListOf("īḥ u", "īr u"),
        "ūru" to arrayListOf("uḥ u", "ur u"),
        "ūru" to arrayListOf("ūḥ u", "ūr u"),
        "eru" to arrayListOf("eḥ u", "er u"),
        "oru" to arrayListOf("oḥ u", "or u"),
        "ṛru" to arrayListOf("ṛḥ u", "ṛr u"),
        "ṝru" to arrayListOf("ṝḥ u", "ṝr u"),
        "ḷru" to arrayListOf("ḷḥ u", "ḷr u"),
        "ḹru" to arrayListOf("ḹḥ u", "ḹr u"),
        "ā u" to arrayListOf("āḥ u"),
        "o u" to arrayListOf("aḥ u"),

        "gū" to arrayListOf("k ū"),
        "ḍū" to arrayListOf("ṭ ū"),
        "dū" to arrayListOf("t ū"),
        "bū" to arrayListOf("p ū"),
        "ṅū" to arrayListOf("ṅ ū"),
        "gū" to arrayListOf("k ū"),
        "ṅṅū" to arrayListOf("ṅ ū"),
        "nū" to arrayListOf("n ū"),
        "nnū" to arrayListOf("n ū"),
        "mū" to arrayListOf("m ū"),
        "irū" to arrayListOf("iḥ ū", "ir ū"),
        "īrū" to arrayListOf("īḥ ū", "īr ū"),
        "ūrū" to arrayListOf("uḥ ū", "ur ū"),
        "ūrū" to arrayListOf("ūḥ ū", "ūr ū"),
        "erū" to arrayListOf("eḥ ū", "er ū"),
        "orū" to arrayListOf("oḥ ū", "or ū"),
        "ṛrū" to arrayListOf("ṛḥ ū", "ṛr ū"),
        "ṝrū" to arrayListOf("ṝḥ ū", "ṝr ū"),
        "ḷrū" to arrayListOf("ḷḥ ū", "ḷr ū"),
        "ḹrū" to arrayListOf("ḹḥ ū", "ḹr ū"),
        "ā ū" to arrayListOf("āḥ ū"),
        "o ū" to arrayListOf("aḥ ū"),

        "ge" to arrayListOf("k e"),
        "ḍe" to arrayListOf("ṭ e"),
        "de" to arrayListOf("t e"),
        "be" to arrayListOf("p e"),
        "ṅe" to arrayListOf("ṅ e"),
        "ge" to arrayListOf("k e"),
        "ṅṅe" to arrayListOf("ṅ e"),
        "ne" to arrayListOf("n e"),
        "nne" to arrayListOf("n e"),
        "me" to arrayListOf("m e"),
        "ire" to arrayListOf("iḥ e", "ir e"),
        "īre" to arrayListOf("īḥ e", "īr e"),
        "ūre" to arrayListOf("uḥ e", "ur e"),
        "ūre" to arrayListOf("ūḥ e", "ūr e"),
        "ere" to arrayListOf("eḥ e", "er e"),
        "ore" to arrayListOf("oḥ e", "or e"),
        "ṛre" to arrayListOf("ṛḥ e", "ṛr e"),
        "ṝre" to arrayListOf("ṝḥ e", "ṝr e"),
        "ḷre" to arrayListOf("ḷḥ e", "ḷr e"),
        "ḹre" to arrayListOf("ḹḥ e", "ḹr e"),
        "ā e" to arrayListOf("āḥ e"),
        "o e" to arrayListOf("aḥ e"),

        "go" to arrayListOf("k o"),
        "ḍo" to arrayListOf("ṭ o"),
        "do" to arrayListOf("t o"),
        "bo" to arrayListOf("p o"),
        "ṅo" to arrayListOf("ṅ o"),
        "go" to arrayListOf("k o"),
        "ṅṅo" to arrayListOf("ṅ o"),
        "no" to arrayListOf("n o"),
        "nno" to arrayListOf("n o"),
        "mo" to arrayListOf("m o"),
        "iro" to arrayListOf("iḥ o", "ir o"),
        "īro" to arrayListOf("īḥ o", "īr o"),
        "ūro" to arrayListOf("uḥ o", "ur o"),
        "ūro" to arrayListOf("ūḥ o", "ūr o"),
        "ero" to arrayListOf("eḥ o", "er o"),
        "oro" to arrayListOf("oḥ o", "or o"),
        "ṛro" to arrayListOf("ṛḥ o", "ṛr o"),
        "ṝro" to arrayListOf("ṝḥ o", "ṝr o"),
        "ḷro" to arrayListOf("ḷḥ o", "ḷr o"),
        "ḹro" to arrayListOf("ḹḥ o", "ḹr o"),
        "ā o" to arrayListOf("āḥ o"),
        "o o" to arrayListOf("aḥ o"),

        "gṛ" to arrayListOf("k ṛ"),
        "ḍṛ" to arrayListOf("ṭ ṛ"),
        "dṛ" to arrayListOf("t ṛ"),
        "bṛ" to arrayListOf("p ṛ"),
        "ṅṛ" to arrayListOf("ṅ ṛ"),
        "gṛ" to arrayListOf("k ṛ"),
        "ṅṅṛ" to arrayListOf("ṅ ṛ"),
        "nṛ" to arrayListOf("n ṛ"),
        "nnṛ" to arrayListOf("n ṛ"),
        "mṛ" to arrayListOf("m ṛ"),
        "irṛ" to arrayListOf("iḥ ṛ", "ir ṛ"),
        "īrṛ" to arrayListOf("īḥ ṛ", "īr ṛ"),
        "ūrṛ" to arrayListOf("uḥ ṛ", "ur ṛ"),
        "ūrṛ" to arrayListOf("ūḥ ṛ", "ūr ṛ"),
        "erṛ" to arrayListOf("eḥ ṛ", "er ṛ"),
        "orṛ" to arrayListOf("oḥ ṛ", "or ṛ"),
        "ṛrṛ" to arrayListOf("ṛḥ ṛ", "ṛr ṛ"),
        "ṝrṛ" to arrayListOf("ṝḥ ṛ", "ṝr ṛ"),
        "ḷrṛ" to arrayListOf("ḷḥ ṛ", "ḷr ṛ"),
        "ḹrṛ" to arrayListOf("ḹḥ ṛ", "ḹr ṛ"),
        "ā ṛ" to arrayListOf("āḥ ṛ"),
        "o ṛ" to arrayListOf("aḥ ṛ"),

        "gṝ" to arrayListOf("k ṝ"),
        "ḍṝ" to arrayListOf("ṭ ṝ"),
        "dṝ" to arrayListOf("t ṝ"),
        "bṝ" to arrayListOf("p ṝ"),
        "ṅṝ" to arrayListOf("ṅ ṝ"),
        "gṝ" to arrayListOf("k ṝ"),
        "ṅṅṝ" to arrayListOf("ṅ ṝ"),
        "nṝ" to arrayListOf("n ṝ"),
        "nnṝ" to arrayListOf("n ṝ"),
        "mṝ" to arrayListOf("m ṝ"),
        "irṝ" to arrayListOf("iḥ ṝ", "ir ṝ"),
        "īrṝ" to arrayListOf("īḥ ṝ", "īr ṝ"),
        "ūrṝ" to arrayListOf("uḥ ṝ", "ur ṝ"),
        "ūrṝ" to arrayListOf("ūḥ ṝ", "ūr ṝ"),
        "erṝ" to arrayListOf("eḥ ṝ", "er ṝ"),
        "orṝ" to arrayListOf("oḥ ṝ", "or ṝ"),
        "ṛrṝ" to arrayListOf("ṛḥ ṝ", "ṛr ṝ"),
        "ṝrṝ" to arrayListOf("ṝḥ ṝ", "ṝr ṝ"),
        "ḷrṝ" to arrayListOf("ḷḥ ṝ", "ḷr ṝ"),
        "ḹrṝ" to arrayListOf("ḹḥ ṝ", "ḹr ṝ"),
        "ā ṝ" to arrayListOf("āḥ ṝ"),
        "o ṝ" to arrayListOf("aḥ ṝ"),

        "gḷ" to arrayListOf("k ḷ"),
        "ḍḷ" to arrayListOf("ṭ ḷ"),
        "dḷ" to arrayListOf("t ḷ"),
        "bḷ" to arrayListOf("p ḷ"),
        "ṅḷ" to arrayListOf("ṅ ḷ"),
        "gḷ" to arrayListOf("k ḷ"),
        "ṅṅḷ" to arrayListOf("ṅ ḷ"),
        "nḷ" to arrayListOf("n ḷ"),
        "nnḷ" to arrayListOf("n ḷ"),
        "mḷ" to arrayListOf("m ḷ"),
        "irḷ" to arrayListOf("iḥ ḷ", "ir ḷ"),
        "īrḷ" to arrayListOf("īḥ ḷ", "īr ḷ"),
        "ūrḷ" to arrayListOf("uḥ ḷ", "ur ḷ"),
        "ūrḷ" to arrayListOf("ūḥ ḷ", "ūr ḷ"),
        "erḷ" to arrayListOf("eḥ ḷ", "er ḷ"),
        "orḷ" to arrayListOf("oḥ ḷ", "or ḷ"),
        "ṛrḷ" to arrayListOf("ṛḥ ḷ", "ṛr ḷ"),
        "ṝrḷ" to arrayListOf("ṝḥ ḷ", "ṝr ḷ"),
        "ḷrḷ" to arrayListOf("ḷḥ ḷ", "ḷr ḷ"),
        "ḹrḷ" to arrayListOf("ḹḥ ḷ", "ḹr ḷ"),
        "ā ḷ" to arrayListOf("āḥ ḷ"),
        "o ḷ" to arrayListOf("aḥ ḷ"),

        "gḹ" to arrayListOf("k ḹ"),
        "ḍḹ" to arrayListOf("ṭ ḹ"),
        "dḹ" to arrayListOf("t ḹ"),
        "bḹ" to arrayListOf("p ḹ"),
        "ṅḹ" to arrayListOf("ṅ ḹ"),
        "gḹ" to arrayListOf("k ḹ"),
        "ṅṅḹ" to arrayListOf("ṅ ḹ"),
        "nḹ" to arrayListOf("n ḹ"),
        "nnḹ" to arrayListOf("n ḹ"),
        "mḹ" to arrayListOf("m ḹ"),
        "irḹ" to arrayListOf("iḥ ḹ", "ir ḹ"),
        "īrḹ" to arrayListOf("īḥ ḹ", "īr ḹ"),
        "ūrḹ" to arrayListOf("uḥ ḹ", "ur ḹ"),
        "ūrḹ" to arrayListOf("ūḥ ḹ", "ūr ḹ"),
        "erḹ" to arrayListOf("eḥ ḹ", "er ḹ"),
        "orḹ" to arrayListOf("oḥ ḹ", "or ḹ"),
        "ṛrḹ" to arrayListOf("ṛḥ ḹ", "ṛr ḹ"),
        "ṝrḹ" to arrayListOf("ṝḥ ḹ", "ṝr ḹ"),
        "ḷrḹ" to arrayListOf("ḷḥ ḹ", "ḷr ḹ"),
        "ḹrḹ" to arrayListOf("ḹḥ ḹ", "ḹr ḹ"),
        "ā ḹ" to arrayListOf("āḥ ḹ"),
        "o ḹ" to arrayListOf("aḥ ḹ"),

        // line 19 (zero)
        "k " to arrayListOf("k  "),
        "ṭ " to arrayListOf("ṭ  "),
        "cch" to arrayListOf("t  "),    // ch
        "bp" to arrayListOf("p  "),
        "ṅ " to arrayListOf("ṅ  "),
        "ñ " to arrayListOf("n  "),
        "ñch" to arrayListOf("n  "),
        "ṃ " to arrayListOf("m  "),
        "iḥ  " to arrayListOf("iḥ  ", "ir  "),
        "īḥ  " to arrayListOf("īḥ  ", "īr  "),
        "ūḥ  " to arrayListOf("uḥ  ", "ur  "),
        "ūḥ  " to arrayListOf("ūḥ  ", "ūr  "),
        "eḥ  " to arrayListOf("eḥ  ", "er  "),
        "oḥ  " to arrayListOf("oḥ  ", "or  "),
        "ṛḥ " to arrayListOf("ṛḥ ", "ṛr "),
        "ṝḥ " to arrayListOf("ṝḥ ", "ṝr "),
        "ḷḥ " to arrayListOf("ḷḥ ", "ḷr "),
        "ḹḥ " to arrayListOf("ḹḥ ", "ḹr "),
        "āḥ  " to arrayListOf("āḥ  "),
        "aḥ  " to arrayListOf("aḥ  ")
    )
    // end table 2.1 consonants
    // ā ī ū ṛ ṝ ḷ ḹ ṭ ḍ ṅ ñ ṇ ś ṣ ṃ ḥ
}